AtalaPrismSDK/Builders/Sources/PolluxBuilder.swift
AtalaPrismSDK/Domain/Sources/BBs/Pollux.swift
AtalaPrismSDK/Domain/Sources/Models/Errors.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnonCredentialDefinition.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnonCredentialSchema.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnoncredsCredentialStack+ProvableCredential.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnoncredsCredentialStack.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnoncredsPresentation.swift
AtalaPrismSDK/Pollux/Sources/Operation/Anoncreds/CreateAnoncredCredentialRequest.swift
AtalaPrismSDK/Pollux/Sources/Operation/Anoncreds/ParseAnoncredsCredentialFromMessage.swift
AtalaPrismSDK/Pollux/Sources/PolluxImpl+CredentialRequest.swift
AtalaPrismSDK/Pollux/Sources/PolluxImpl+ParseCredential.swift
AtalaPrismSDK/Pollux/Sources/PolluxImpl.swift
AtalaPrismSDK/Pollux/Tests/AnoncredsTests.swift
AtalaPrismSDK/Pollux/Tests/Mocks/MockIssuer.swift
AtalaPrismSDK/Pollux/Tests/Mocks/MockPluto.swift
AtalaPrismSDK/PrismAgent/Sources/PrismAgent.swift
Package.swift

This will add implementation so we can create presentation with a anoncred credential.
Fixes #ATL-5203

feat(pollux): add anoncreds prooving implementation

---

AtalaPrismSDK/Domain/Sources/BBs/Pluto.swift
AtalaPrismSDK/Pluto/Sources/Domain/Providers/LinkSecretProvider.swift
AtalaPrismSDK/Pluto/Sources/PersistentStorage/DAO/CDDIDPrivateKeyDAO+DIDPrivateKeyProvider.swift
AtalaPrismSDK/Pluto/Sources/PersistentStorage/DAO/CDDIDPrivateKeyDAO+DIDPrivateKeyStore.swift
AtalaPrismSDK/Pluto/Sources/PersistentStorage/DAO/CDDatabaseKeyDAO.swift
AtalaPrismSDK/Pluto/Sources/PersistentStorage/DAO/CDKeyDAO+LinkSecretProvider.swift
AtalaPrismSDK/Pluto/Sources/PersistentStorage/DAO/CDKeyDAO+LinkSecretStore.swift
AtalaPrismSDK/Pluto/Sources/PersistentStorage/DAO/CDKeyDAO.swift
AtalaPrismSDK/Pluto/Sources/PersistentStorage/DAO/CDKeychainKeyDAO.swift
AtalaPrismSDK/Pluto/Sources/PlutoImpl+Public.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnonCredentialSchema.swift
AtalaPrismSDK/Pollux/Sources/Operation/Anoncreds/ParseAnoncredsCredentialFromMessage.swift
AtalaPrismSDK/Pollux/Tests/Mocks/MockPluto.swift
AtalaPrismSDK/PrismAgent/Sources/PrismAgent+Credentials.swift
AtalaPrismSDK/PrismAgent/Sources/PrismAgent+Proof.swift
AtalaPrismSDK/PrismAgent/Sources/PrismAgent.swift
AtalaPrismSDK/PrismAgent/Sources/Protocols/Connection/DownloadDataWithResolver.swift
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo/Modules/SetupPrismAgent/SetupPrismAgentViewModel.swift
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo/Modules/WalletDemo2/Main/Main2Router.swift
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo/Modules/WalletDemo2/Messages/MessageDetail/MessageDetailViewModel.swift

ZKP Verification.
This PR also fixes a issue with Link secret that was not saving correctly.
And Updates the demo app for the zkp verification code.
Fixes ATL-5203

feat(pollux): zkp verification

---

AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnonCredentialDefinition.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnonCredentialSchema.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnoncredsCredentialStack.swift
AtalaPrismSDK/Pollux/Sources/Models/AnonCreds/AnoncredsPresentation.swift
AtalaPrismSDK/Pollux/Sources/Operation/Anoncreds/ParseAnoncredsCredentialFromMessage.swift

Our e2e tests are failing because the agent didn't update this part. So kind of regressing here but will reenable after.

fix: schema download optional

---

.github/workflows/build.yml
README.md
build_test.sh

Enables coveralls integration
Fixes #<issue number>

test: add coveralls integration

---

EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+Credentials.swift
EdgeAgentSDK/EdgeAgent/Tests/AnoncredsPresentationFlowTest.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+Presentation.swift

Add ability to add predicates on anoncreds presentation requests.
Fixes ATL-6848 ATL-6517

feat(pollux): add anoncreds predicate on requests

---

Package.swift

Hey there, this is just a simple change that I made to help fix the setup on my mac for cloning the sample project. Both my friend (@Jack-Severson) and I were having issues with building the demo wallet app in Xcode 15.4 or adding the package to a new project due to an issue with fetching `swift-protobuf`.
I ultimately narrowed the issue down to the Package.swift file using the SSH format for cloning the `swift-protobuf` package and timing out on our machines. I changes the the format to HTTPS and was then able to successfully resolve dependencies and build the app.

fix: Update Package.swift to use HTTPS for swift-protobuf dependency

---

EdgeAgentSDK/Apollo/Sources/ApolloImpl+KeyRestoration.swift
EdgeAgentSDK/Apollo/Sources/ApolloImpl+Public.swift
EdgeAgentSDK/Apollo/Sources/Model/Ed25519Key.swift
EdgeAgentSDK/Apollo/Sources/Model/LinkSecret.swift
EdgeAgentSDK/Apollo/Sources/Model/Secp256k1Key.swift
EdgeAgentSDK/Apollo/Sources/Model/X25519Key.swift
EdgeAgentSDK/Apollo/Sources/Operations/CreateEd25519KeyPairOperation.swift
EdgeAgentSDK/Apollo/Sources/Operations/CreateX25519KeyPairOperation.swift
EdgeAgentSDK/Castor/Tests/PrismDIDPublicKeyTests.swift
EdgeAgentSDK/Domain/Sources/Models/KeyManagement/DerivableKey.swift
EdgeAgentSDK/Domain/Sources/Models/KeyManagement/StorableKey.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+Backup.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+DIDHigherFucntions.swift
EdgeAgentSDK/EdgeAgent/Sources/Helpers/EdgeAgentDerivationPath.swift
EdgeAgentSDK/EdgeAgent/Tests/CheckTest.swift
EdgeAgentSDK/EdgeAgent/Tests/DerivationPathTests.swift
EdgeAgentSDK/Pluto/Sources/Domain/StorableKeyModel.swift
EdgeAgentSDK/Pluto/Sources/PersistentStorage/DAO/CDKeyDAO.swift
EdgeAgentSDK/Pluto/Sources/PersistentStorage/Models/CDKey+CoreDataProperties.swift
EdgeAgentSDK/Pluto/Sources/PersistentStorage/Models/CDKeychainKey+CoreDataProperties.swift
EdgeAgentSDK/Pluto/Sources/Resources/PrismPluto.xcdatamodeld/.xccurrentversion
EdgeAgentSDK/Pluto/Sources/Resources/PrismPluto.xcdatamodeld/PrismPlutoV2.xcdatamodel/contents
EdgeAgentSDK/Pluto/Tests/Helper/PrivateKey+Test.swift

feat(agent): add new agent derivation path

---

EdgeAgentSDK/Castor/Sources/DID/PrismDID/PrismDIDPublicKey.swift
EdgeAgentSDK/Castor/Sources/Operations/CreatePrismDIDOperation.swift
EdgeAgentSDK/Castor/Tests/PrismDIDPublicKeyTests.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+DIDHigherFucntions.swift

Add capacity so you can create and resolve prism dids with ed25519 and x25519 keys
Fixes ATL-7160

feat(castor): add capacity so you can create and resolve prism dids with ed25519 and x25519 keys

---

EdgeAgentSDK/Castor/Sources/Resolvers/LongFormPrismDIDResolver.swift
EdgeAgentSDK/Castor/Sources/Resolvers/PeerDIDResolver.swift
EdgeAgentSDK/Castor/Tests/DIDParserTests.swift
EdgeAgentSDK/Domain/Sources/AnyCodable.swift
EdgeAgentSDK/Domain/Sources/Models/Message+Codable.swift
EdgeAgentSDK/Domain/Sources/Models/MessageAttachment.swift
EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Credentials.swift
EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Invitations.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/Invitation/V2/OutOfBandInvitation.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/IssueCredential/OfferCredential.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/Pickup/PickupRunner.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/ProofPresentation/RequestPresentation.swift
EdgeAgentSDK/EdgeAgent/Tests/Helper/MockMediatorHandler.swift
EdgeAgentSDK/EdgeAgent/Tests/Helper/MockMercury.swift
EdgeAgentSDK/EdgeAgent/Tests/PrismOnboardingInvitationTests.swift
EdgeAgentSDK/Mercury/Sources/Forward/ForwardMessage.swift
EdgeAgentSDK/Mercury/Sources/Helpers/DIDCommMessage+DomainParse.swift
EdgeAgentSDK/Pollux/Sources/Models/AnonCreds/AnoncredsCredentialStack+ProvableCredential.swift
EdgeAgentSDK/Pollux/Sources/Models/JWT/JWTCredential+ProofableCredential.swift
EdgeAgentSDK/Pollux/Sources/Models/JWT/JWTPayload+Codable.swift
EdgeAgentSDK/Pollux/Sources/Models/JWT/JWTPayload.swift
EdgeAgentSDK/Pollux/Sources/Models/SDJWT/SDJWT+ProvableCredential.swift
EdgeAgentSDK/Pollux/Sources/Models/W3C/W3CVerifiableCredential+Codable.swift
EdgeAgentSDK/Pollux/Sources/Models/W3C/W3CVerifiableCredential.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+CredentialRequest.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+CredentialVerification.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+ParseCredential.swift

This PR adds connectionless issuance and replaces the [PR](https://github.com/hyperledger/identus-edge-agent-sdk-swift/pull/163) since it is already with new refactoring so it adds connectionless issuance and presentation.

feat(edgeagent): adds support for connectionless issuance and presentation

---

EdgeAgentSDK/Apollo/Sources/ApolloImpl+Public.swift
EdgeAgentSDK/Apollo/Sources/Model/Ed25519Key.swift
EdgeAgentSDK/Apollo/Sources/Model/Secp256k1Key+Exportable.swift
EdgeAgentSDK/Apollo/Sources/Model/Secp256k1Key.swift
EdgeAgentSDK/Apollo/Sources/Model/X25519Key.swift
EdgeAgentSDK/Apollo/Sources/Operations/CreateEd25519KeyPairOperation.swift
EdgeAgentSDK/Apollo/Sources/Operations/CreateSec256k1KeyPairOperation.swift
EdgeAgentSDK/Apollo/Sources/Operations/CreateX25519KeyPairOperation.swift
EdgeAgentSDK/Castor/Sources/Resolvers/PeerDIDResolver.swift
EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Invitations.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+DIDHigherFucntions.swift
EdgeAgentSDK/EdgeAgent/Tests/PresentationExchangeTests.swift
EdgeAgentSDK/Mercury/Sources/DIDCommWrappers/DIDCommDIDResolverWrapper.swift
EdgeAgentSDK/Pollux/Sources/Models/JWT/JWTPresentation.swift
EdgeAgentSDK/Pollux/Sources/Operation/JWT/CreateJWTCredentialRequest.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+CredentialVerification.swift
Package.swift

feat(edgeAgent): KID will be present on any signed JWTs

---

EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Credentials.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+Credentials.swift

There was a func with an unneeded async, removing.

fix: removing unneeded async from func

---

E2E/e2eTests/Source/Workflows/EdgeAgentWorkflow.swift

Fixes the e2e test for revoked jwt verification

test: fixes revoked jwt verification test

---

.github/workflows/build.yml
Package.swift
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo.xcodeproj/project.pbxproj
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo/Modules/Verifier/PresentationsDetail/PresentationDetailViewModel.swift
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo/Modules/WalletDemo2/Messages/MessageDetail/MessageDetailViewModel.swift
build_test.sh

There is a problem with this package right now since it depends of a branch. Swift package doesnt allow that for production.
https://github.com/hyperledger/identus-edge-agent-sdk-swift/issues/180

fix: swift package complains of having a dependency on a branch

---

EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Credentials.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/IssueCredential/IssueCredential.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/IssueCredential/OfferCredential.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/IssueCredential/ProposeCredential.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/IssueCredential/RequestCredential.swift
EdgeAgentSDK/EdgeAgent/Sources/Protocols/IssueCredential/RevocationNotification.swift
EdgeAgentSDK/EdgeAgent/Tests/IssueCredentialTests.swift
EdgeAgentSDK/EdgeAgent/Tests/RequestCredentialTests.swift

feat(agent): the body on issue credential protocol messages can be null
(https://github.com/hyperledger/identus/issues/115)

feat(agent): the body on issue credential protocol messages can be null

---

EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent.swift

Summarize the changes you're submitting in a few sentences, including Jira ticket ATL-xxxx if applicable.
Link to any discussion, related issues and bug reports to give the context to help the reviewer understand the PR.
Fix typo in DIDCommAgent State enum value.  Should not break SDK however potential for downstream breaking change if users have relied on the misspelling in their consumer code.
Link to existing ADR (Architecture Decision Record), if any. If relevant, describe other approaches explored and the selected approach. Documenting why the methods were not selected will create a knowledge base for future reference, helping prevent others from revisiting less optimal ideas.
- [] I have added tests that prove my fix is effective or that my feature works

refactor(experience): fix didcommagent state enum typo

---

.github/CODEOWNERS
.github/workflows/build.yml
.github/workflows/releaseDocumentation.yml

Fix of the CI for the new repo location.

ci: fix ci and documentation

---

EdgeAgentSDK/Castor/Sources/CastorImpl+Public.swift
EdgeAgentSDK/Castor/Sources/DID/PrismDID/PrismDIDPublicKey.swift
EdgeAgentSDK/Castor/Sources/Operations/CreatePeerDIDOperation.swift
EdgeAgentSDK/Castor/Sources/Operations/CreatePrismDIDOperation.swift
EdgeAgentSDK/Castor/Sources/Resolvers/LongFormPrismDIDResolver.swift
EdgeAgentSDK/Domain/Sources/BBs/Castor.swift
EdgeAgentSDK/Domain/Sources/BBs/Pollux.swift
EdgeAgentSDK/Domain/Sources/Models/Errors.swift
EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Credentials.swift
EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+DIDs.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+Credentials.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+DIDHigherFucntions.swift
EdgeAgentSDK/EdgeAgent/Sources/OIDCAgent/OIDCAgent+DIDs.swift
EdgeAgentSDK/EdgeAgent/Tests/BackupWalletTests.swift
EdgeAgentSDK/EdgeAgent/Tests/CheckTest.swift
EdgeAgentSDK/EdgeAgent/Tests/Helper/Castor+Testing.swift
EdgeAgentSDK/Pollux/Sources/Operation/SDJWT/CreateSDJWTCrendentialRequest.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+CredentialRequest.swift
EdgeAgentSDK/Pollux/Tests/Mocks/MockCastor.swift
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo.xcodeproj/project.pbxproj
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo/Modules/WalletDemo2/Credentials/CredentialsList/CredentialListViewModel.swift
Sample/AtalaPrismWalletDemo/AtalaPrismWalletDemo/Modules/WalletDemo2/Mediator/MediatorPage/MediatorPageView.swift

now castor and agents can create a did with any keys
This PR also fixes a bug with the issuance flow on SD-JWT.

feat(castor): now castor and agents can create a did with any keys

---

EdgeAgentSDK/Pollux/Sources/PolluxImpl+CredentialRequest.swift

This is a workaround since prism did master did does not show in the DIDDocument.

fix: a workaround prism did since the master key should not be handled

---

EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Credentials.swift

Anoncreds had a missing parameter

fix: anoncreds missing thid

---

EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Proof.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+DIDHigherFucntions.swift
EdgeAgentSDK/EdgeAgent/Sources/EdgeAgent+Proof.swift
EdgeAgentSDK/EdgeAgent/Tests/PresentationExchangeTests.swift
EdgeAgentSDK/Pollux/Sources/Models/JWT/JWTPresentation.swift
EdgeAgentSDK/Pollux/Sources/Models/SDJWT/SDJWTPresentation.swift

There was an issue because master key should not be available with prism did document. This is a fix for the moment further refactoring is needed.

fix: presentation now selects the proper key

---

EdgeAgentSDK/Pluto/Sources/PersistentStorage/DAO/CDMessageDAO+MessageStore.swift
build_test.sh

Changed to a batchUpdate to see if it handles better and does not crash

fix: a bug was introduced that was not capture in the tests, having this inside a future does not run unfortunatelly.

---

EdgeAgentSDK/Domain/Sources/Models/Credentials/Credential.swift
EdgeAgentSDK/EdgeAgent/Sources/DIDCommAgent/DIDCommAgent+Credentials.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+Presentation.swift

Now sdjwt will have its own format as credential type

feat: add sdjwt as credential type

---

EdgeAgentSDK/EdgeAgent/Tests/PresentationExchangeTests.swift
EdgeAgentSDK/Pollux/Sources/PolluxImpl+Presentation.swift
build_test.sh

There was as well a fix for the current CI that was not failing on test fails

fix: presentation definition broken
